<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ASA.ServerManager.Application\ASA.ServerManager.Application.csproj" />
    <ProjectReference Include="..\ASA.ServerManager.Domain\ASA.ServerManager.Domain.csproj" />
    <ProjectReference Include="..\ASA.ServerManager.Infrastructure\ASA.ServerManager.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\definitions\game-settings.json" Link="definitions\game-settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\definitions\game-settings.schema.json" Link="definitions\game-settings.schema.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
