PRAGMA foreign_keys=ON;

CREATE TABLE meta_debut_ability_snapshot_build(
  build_id INTEGER PRIMARY KEY,
  builder_version TEXT NOT NULL,
  schema_version TEXT NOT NULL,
  index_base_db_path TEXT NOT NULL,
  official_runperf_db_path TEXT NOT NULL,
  started_at TEXT NOT NULL,
  finished_at TEXT,
  status TEXT NOT NULL,
  source_year_min INTEGER,
  source_year_max INTEGER,
  target_runner_count INTEGER,
  true_first_start_count INTEGER,
  prior_start_no_scored_history_count INTEGER,
  message TEXT
);

CREATE TABLE debut_target_runner(
  race_date TEXT NOT NULL,
  race_key TEXT NOT NULL,
  horse_no INTEGER NOT NULL,
  horse_id TEXT,
  year INTEGER NOT NULL,
  venue_code TEXT,
  surface_code TEXT,
  distance_m INTEGER,
  jockey_code TEXT,
  trainer_code TEXT,
  current_carried_weight REAL,
  race_mean_carried_weight REAL,
  weight_relative REAL,
  prior_start_count INTEGER NOT NULL,
  is_true_first_start INTEGER NOT NULL,
  race_context_availability TEXT NOT NULL,
  profile_data_date TEXT,
  profile_prior_day_available INTEGER NOT NULL,
  profile_same_day_observation_exists INTEGER NOT NULL,
  sire_name TEXT,
  broodmare_sire_name TEXT,
  sire_line_code TEXT,
  broodmare_sire_line_code TEXT,
  dam_name TEXT,
  birth_date TEXT,
  sex_code TEXT,
  age_in_months REAL,
  as_of_exclusive TEXT NOT NULL,
  feature_builder_version TEXT NOT NULL,
  formula_version TEXT NOT NULL,
  source_snapshot TEXT NOT NULL,
  calculated_at TEXT NOT NULL,
  validation_status TEXT NOT NULL,
  PRIMARY KEY(race_key,horse_no)
);

CREATE TABLE debut_pedigree_feature(
  race_key TEXT NOT NULL,
  horse_no INTEGER NOT NULL,
  sire_debut_runperf_raw REAL,
  sire_debut_n INTEGER NOT NULL,
  sire_debut_missing INTEGER NOT NULL,
  broodmare_sire_debut_runperf_raw REAL,
  broodmare_sire_debut_n INTEGER NOT NULL,
  broodmare_sire_debut_missing INTEGER NOT NULL,
  sire_line_debut_runperf_raw REAL,
  sire_line_debut_n INTEGER NOT NULL,
  sire_line_debut_missing INTEGER NOT NULL,
  broodmare_sire_line_debut_runperf_raw REAL,
  broodmare_sire_line_debut_n INTEGER NOT NULL,
  broodmare_sire_line_debut_missing INTEGER NOT NULL,
  sire_surface_debut_runperf_raw REAL,
  sire_surface_debut_n INTEGER NOT NULL,
  sire_surface_debut_missing INTEGER NOT NULL,
  broodmare_sire_surface_debut_runperf_raw REAL,
  broodmare_sire_surface_debut_n INTEGER NOT NULL,
  broodmare_sire_surface_debut_missing INTEGER NOT NULL,
  sire_distance_d200_raw REAL, sire_distance_d200_n INTEGER NOT NULL, sire_distance_d200_neff REAL, sire_distance_d200_missing INTEGER NOT NULL,
  sire_distance_d400_raw REAL, sire_distance_d400_n INTEGER NOT NULL, sire_distance_d400_neff REAL, sire_distance_d400_missing INTEGER NOT NULL,
  sire_distance_d600_raw REAL, sire_distance_d600_n INTEGER NOT NULL, sire_distance_d600_neff REAL, sire_distance_d600_missing INTEGER NOT NULL,
  sire_distance_d800_raw REAL, sire_distance_d800_n INTEGER NOT NULL, sire_distance_d800_neff REAL, sire_distance_d800_missing INTEGER NOT NULL,
  broodmare_sire_distance_d200_raw REAL, broodmare_sire_distance_d200_n INTEGER NOT NULL, broodmare_sire_distance_d200_neff REAL, broodmare_sire_distance_d200_missing INTEGER NOT NULL,
  broodmare_sire_distance_d400_raw REAL, broodmare_sire_distance_d400_n INTEGER NOT NULL, broodmare_sire_distance_d400_neff REAL, broodmare_sire_distance_d400_missing INTEGER NOT NULL,
  broodmare_sire_distance_d600_raw REAL, broodmare_sire_distance_d600_n INTEGER NOT NULL, broodmare_sire_distance_d600_neff REAL, broodmare_sire_distance_d600_missing INTEGER NOT NULL,
  broodmare_sire_distance_d800_raw REAL, broodmare_sire_distance_d800_n INTEGER NOT NULL, broodmare_sire_distance_d800_neff REAL, broodmare_sire_distance_d800_missing INTEGER NOT NULL,
  FOREIGN KEY(race_key,horse_no) REFERENCES debut_target_runner(race_key,horse_no),
  PRIMARY KEY(race_key,horse_no)
);

CREATE TABLE debut_training_feature(
  race_key TEXT NOT NULL,
  horse_no INTEGER NOT NULL,
  training_date TEXT,
  workout_count INTEGER,
  workout_course_code TEXT,
  effort_code TEXT,
  chase_state_code TEXT,
  rider_type_code TEXT,
  furlong_count INTEGER,
  first_segment_sec REAL,
  middle_segment_sec REAL,
  final_segment_sec REAL,
  jrdb_first_segment_index INTEGER,
  jrdb_middle_segment_index INTEGER,
  jrdb_final_segment_index INTEGER,
  jrdb_workout_index_cha INTEGER,
  pair_result_code TEXT,
  pair_effort_code TEXT,
  pair_age INTEGER,
  pair_class_code TEXT,
  training_type_code TEXT,
  training_course_type_code TEXT,
  used_slope INTEGER,
  used_wood INTEGER,
  used_dirt INTEGER,
  used_turf INTEGER,
  used_pool INTEGER,
  used_jump INTEGER,
  used_polytrack INTEGER,
  training_distance_code TEXT,
  training_focus_code TEXT,
  jrdb_workout_index_cyb INTEGER,
  finish_index INTEGER,
  training_volume_code TEXT,
  finish_change_code TEXT,
  training_evaluation_code TEXT,
  week_ago_workout_index INTEGER,
  week_ago_course_code TEXT,
  cha_missing INTEGER NOT NULL,
  cyb_missing INTEGER NOT NULL,
  FOREIGN KEY(race_key,horse_no) REFERENCES debut_target_runner(race_key,horse_no),
  PRIMARY KEY(race_key,horse_no)
);

CREATE TABLE debut_people_prior_feature(
  race_key TEXT NOT NULL,
  horse_no INTEGER NOT NULL,
  jockey_debut_runperf_raw REAL,
  jockey_debut_n INTEGER NOT NULL,
  jockey_debut_missing INTEGER NOT NULL,
  trainer_debut_runperf_raw REAL,
  trainer_debut_n INTEGER NOT NULL,
  trainer_debut_missing INTEGER NOT NULL,
  FOREIGN KEY(race_key,horse_no) REFERENCES debut_target_runner(race_key,horse_no),
  PRIMARY KEY(race_key,horse_no)
);

CREATE TABLE debut_current_result(
  race_key TEXT NOT NULL,
  horse_no INTEGER NOT NULL,
  score_status TEXT,
  official_runperf_raw REAL,
  score_provenance TEXT,
  PRIMARY KEY(race_key,horse_no),
  FOREIGN KEY(race_key,horse_no) REFERENCES debut_target_runner(race_key,horse_no)
);

CREATE INDEX ix_debut_target_date ON debut_target_runner(race_date,race_key,horse_no);
CREATE INDEX ix_debut_target_horse ON debut_target_runner(horse_id,race_date);
CREATE INDEX ix_debut_target_sire ON debut_target_runner(sire_name,race_date);
CREATE INDEX ix_debut_target_damsire ON debut_target_runner(broodmare_sire_name,race_date);
