PRAGMA foreign_keys=ON;

-- JRDB PWA independent index base schema v0.1
-- Purpose: time-aware longitudinal source layer for RunPerf / Ability / Edge research.
-- This database is intentionally separate from Analysis Lite / Stats Mart / PWA Fact Lite.

CREATE TABLE meta_index_base_build(
  build_id INTEGER PRIMARY KEY,
  builder_version TEXT NOT NULL,
  schema_version TEXT NOT NULL,
  started_at TEXT NOT NULL,
  finished_at TEXT,
  status TEXT NOT NULL,
  years_json TEXT NOT NULL,
  source_manifest_json TEXT,
  race_count INTEGER,
  race_result_context_count INTEGER,
  runner_pre_count INTEGER,
  runner_result_count INTEGER,
  workout_count INTEGER,
  training_count INTEGER,
  profile_observation_count INTEGER,
  anomaly_count INTEGER,
  message TEXT
);

CREATE TABLE meta_index_base_source(
  source_id INTEGER PRIMARY KEY,
  build_id INTEGER NOT NULL,
  source_kind TEXT NOT NULL,
  year INTEGER NOT NULL,
  archive_path TEXT NOT NULL,
  archive_sha256 TEXT,
  archive_size_bytes INTEGER,
  member_count INTEGER,
  imported_at TEXT NOT NULL,
  FOREIGN KEY(build_id) REFERENCES meta_index_base_build(build_id)
);

CREATE TABLE meta_index_base_anomaly(
  anomaly_id INTEGER PRIMARY KEY,
  build_id INTEGER NOT NULL,
  severity TEXT NOT NULL,
  anomaly_type TEXT NOT NULL,
  source_kind TEXT,
  year INTEGER,
  business_key TEXT,
  detail TEXT,
  detected_at TEXT NOT NULL,
  FOREIGN KEY(build_id) REFERENCES meta_index_base_build(build_id)
);

CREATE TABLE race_context(
  race_key TEXT PRIMARY KEY,
  race_date TEXT NOT NULL,
  year INTEGER NOT NULL,
  venue_code TEXT NOT NULL,
  race_no INTEGER NOT NULL,
  start_time TEXT,
  distance_m INTEGER,
  surface_code TEXT,
  turn_code TEXT,
  inner_outer_code TEXT,
  race_type_code TEXT,
  race_condition_code TEXT,
  race_symbol_code TEXT,
  weight_condition_code TEXT,
  grade_code TEXT,
  race_name TEXT,
  declared_field_size INTEGER,
  course_code TEXT,
  meeting_area_code TEXT,
  availability_class TEXT NOT NULL CHECK(availability_class IN ('PRE_RACE','CURRENT_RESULT_FALLBACK')),
  source_kind TEXT NOT NULL,
  source_member TEXT,
  record_hash TEXT NOT NULL
);

CREATE TABLE race_result_context(
  race_key TEXT PRIMARY KEY,
  track_condition_code TEXT,
  weather_code TEXT,
  source_member TEXT,
  semantic_hash TEXT NOT NULL,
  FOREIGN KEY(race_key) REFERENCES race_context(race_key)
);

CREATE TABLE runner_pre(
  race_key TEXT NOT NULL,
  horse_no INTEGER NOT NULL,
  horse_id TEXT,
  horse_name TEXT,
  frame_no INTEGER,
  sex_code TEXT,
  jockey_name TEXT,
  jockey_code TEXT,
  trainer_name TEXT,
  trainer_code TEXT,
  carried_weight_kg REAL,
  running_style_code TEXT,
  distance_aptitude_code TEXT,
  uptrend_code TEXT,
  rotation_interval INTEGER,
  pre_idm REAL,
  training_score REAL,
  stable_score REAL,
  training_arrow_code TEXT,
  stable_evaluation_code TEXT,
  blinker_code TEXT,
  condition_class_code TEXT,
  body_weight_pre_kg INTEGER,
  body_weight_change_pre_kg INTEGER,
  start_index REAL,
  slow_start_rate REAL,
  stable_run_no INTEGER,
  stable_entry_date TEXT,
  stable_days_before INTEGER,
  expected_ten_index REAL,
  expected_pace_index REAL,
  expected_last3f_index REAL,
  expected_position_index REAL,
  expected_race_pace TEXT,
  source_member TEXT,
  record_hash TEXT NOT NULL,
  PRIMARY KEY(race_key, horse_no),
  FOREIGN KEY(race_key) REFERENCES race_context(race_key)
);

CREATE TABLE runner_previous_link(
  race_key TEXT NOT NULL,
  horse_no INTEGER NOT NULL,
  sequence INTEGER NOT NULL CHECK(sequence BETWEEN 1 AND 5),
  prev_result_key TEXT,
  prev_race_key TEXT,
  PRIMARY KEY(race_key, horse_no, sequence),
  FOREIGN KEY(race_key, horse_no) REFERENCES runner_pre(race_key, horse_no)
);

CREATE TABLE runner_result(
  race_key TEXT NOT NULL,
  horse_no INTEGER NOT NULL,
  result_key TEXT,
  horse_id TEXT,
  horse_name TEXT,
  finish INTEGER,
  abnormal_code TEXT,
  time_sec REAL,
  carried_weight_kg REAL,
  jockey_name TEXT,
  jockey_code TEXT,
  trainer_name TEXT,
  trainer_code TEXT,
  final_win_odds REAL,
  final_win_popularity INTEGER,
  final_place_odds_lower REAL,
  idm INTEGER,
  raw_score INTEGER,
  jrdb_track_diff INTEGER,
  jrdb_pace_score INTEGER,
  jrdb_slow_start_score INTEGER,
  jrdb_position_score INTEGER,
  jrdb_trouble_score INTEGER,
  jrdb_early_trouble_score INTEGER,
  jrdb_mid_trouble_score INTEGER,
  jrdb_late_trouble_score INTEGER,
  jrdb_race_score INTEGER,
  course_lane_code TEXT,
  result_uptrend_code TEXT,
  result_class_code TEXT,
  body_condition_code TEXT,
  mood_code TEXT,
  race_pace TEXT,
  horse_pace TEXT,
  front_index REAL,
  last3f_index REAL,
  pace_index REAL,
  race_pace_index REAL,
  first_second_time_diff_sec REAL,
  first3f_sec REAL,
  last3f_sec REAL,
  corner1 INTEGER,
  corner2 INTEGER,
  corner3 INTEGER,
  corner4 INTEGER,
  first3f_leader_diff_sec REAL,
  last3f_leader_diff_sec REAL,
  body_weight_kg INTEGER,
  body_weight_change_kg INTEGER,
  weather_code TEXT,
  course_code TEXT,
  race_running_style_code TEXT,
  fourth_corner_lane_code TEXT,
  win_payout INTEGER,
  place_payout INTEGER,
  source_member TEXT,
  record_hash TEXT NOT NULL,
  PRIMARY KEY(race_key, horse_no),
  UNIQUE(result_key),
  FOREIGN KEY(race_key) REFERENCES race_context(race_key)
);

CREATE TABLE workout_main(
  race_key TEXT NOT NULL,
  horse_no INTEGER NOT NULL,
  training_date TEXT,
  weekday TEXT,
  workout_count INTEGER,
  course_code TEXT,
  effort_code TEXT,
  chase_state_code TEXT,
  rider_type_code TEXT,
  furlong_count INTEGER,
  first_segment_sec REAL,
  middle_segment_sec REAL,
  final_segment_sec REAL,
  jrdb_first_segment_index INTEGER,
  jrdb_middle_segment_index INTEGER,
  jrdb_final_segment_index INTEGER,
  jrdb_workout_index INTEGER,
  pair_result_code TEXT,
  pair_effort_code TEXT,
  pair_age INTEGER,
  pair_class_code TEXT,
  source_member TEXT,
  record_hash TEXT NOT NULL,
  PRIMARY KEY(race_key, horse_no),
  FOREIGN KEY(race_key) REFERENCES race_context(race_key)
);

CREATE TABLE training_analysis(
  race_key TEXT NOT NULL,
  horse_no INTEGER NOT NULL,
  training_type_code TEXT,
  training_course_type_code TEXT,
  used_slope INTEGER,
  used_wood INTEGER,
  used_dirt INTEGER,
  used_turf INTEGER,
  used_pool INTEGER,
  used_jump INTEGER,
  used_polytrack INTEGER,
  training_distance_code TEXT,
  training_focus_code TEXT,
  jrdb_workout_index INTEGER,
  finish_index INTEGER,
  training_volume_code TEXT,
  finish_change_code TEXT,
  training_evaluation_code TEXT,
  week_ago_workout_index INTEGER,
  week_ago_course_code TEXT,
  source_member TEXT,
  record_hash TEXT NOT NULL,
  PRIMARY KEY(race_key, horse_no),
  FOREIGN KEY(race_key) REFERENCES race_context(race_key)
);

CREATE TABLE horse_profile_observation(
  horse_id TEXT NOT NULL,
  data_date TEXT NOT NULL,
  horse_name TEXT,
  sex_code TEXT,
  sire_name TEXT,
  dam_name TEXT,
  broodmare_sire_name TEXT,
  birth_date TEXT,
  sire_birth_year INTEGER,
  dam_birth_year INTEGER,
  broodmare_sire_birth_year INTEGER,
  breeder_name TEXT,
  breeding_place TEXT,
  sire_line_code TEXT,
  broodmare_sire_line_code TEXT,
  semantic_hash TEXT NOT NULL,
  source_member TEXT,
  record_hash TEXT NOT NULL,
  PRIMARY KEY(horse_id, data_date, semantic_hash)
);

CREATE INDEX ix_index_race_date ON race_context(race_date);
CREATE INDEX ix_index_race_course ON race_context(year, venue_code, surface_code, distance_m);
CREATE INDEX ix_index_race_result_condition ON race_result_context(track_condition_code);
CREATE INDEX ix_index_pre_horse ON runner_pre(horse_id, race_key);
CREATE INDEX ix_index_pre_jockey ON runner_pre(jockey_code, race_key);
CREATE INDEX ix_index_pre_trainer ON runner_pre(trainer_code, race_key);
CREATE INDEX ix_index_prev_result ON runner_previous_link(prev_result_key);
CREATE INDEX ix_index_prev_race ON runner_previous_link(prev_race_key);
CREATE INDEX ix_index_result_horse ON runner_result(horse_id, result_key);
CREATE INDEX ix_index_result_date_key ON runner_result(result_key);
CREATE INDEX ix_index_profile_asof ON horse_profile_observation(horse_id, data_date);

CREATE VIEW v_runner_longitudinal_base AS
SELECT
  r.race_date,
  r.year,
  r.venue_code,
  r.race_no,
  r.race_key,
  r.start_time,
  r.distance_m,
  r.surface_code,
  r.turn_code,
  r.inner_outer_code,
  r.race_type_code,
  r.race_condition_code,
  r.race_symbol_code,
  r.weight_condition_code,
  r.grade_code,
  r.race_name,
  r.declared_field_size,
  r.course_code,
  r.availability_class AS race_context_availability,
  rc.track_condition_code,
  rc.weather_code,
  p.horse_no,
  p.frame_no,
  p.horse_id,
  p.horse_name,
  p.sex_code,
  p.jockey_name AS pre_jockey_name,
  p.jockey_code AS pre_jockey_code,
  p.trainer_name AS pre_trainer_name,
  p.trainer_code AS pre_trainer_code,
  p.carried_weight_kg AS pre_carried_weight_kg,
  p.running_style_code AS pre_running_style_code,
  p.distance_aptitude_code,
  p.uptrend_code,
  p.rotation_interval,
  p.pre_idm,
  p.training_score,
  p.stable_score,
  p.training_arrow_code,
  p.stable_evaluation_code,
  p.blinker_code,
  p.condition_class_code,
  p.body_weight_pre_kg,
  p.body_weight_change_pre_kg,
  p.start_index,
  p.slow_start_rate,
  p.stable_run_no,
  p.stable_entry_date,
  p.stable_days_before,
  x.result_key,
  x.finish,
  x.abnormal_code,
  x.time_sec,
  x.idm,
  x.raw_score,
  x.first3f_sec,
  x.last3f_sec,
  x.corner1,
  x.corner2,
  x.corner3,
  x.corner4,
  x.body_weight_kg,
  x.body_weight_change_kg,
  x.final_win_odds,
  x.final_win_popularity,
  x.win_payout,
  x.place_payout,
  w.training_date,
  w.course_code AS workout_course_code,
  w.effort_code,
  w.chase_state_code,
  w.rider_type_code,
  w.furlong_count,
  w.first_segment_sec,
  w.middle_segment_sec,
  w.final_segment_sec,
  w.jrdb_workout_index,
  t.training_type_code,
  t.training_course_type_code,
  t.finish_index,
  t.training_volume_code,
  t.finish_change_code,
  t.training_evaluation_code,
  t.week_ago_workout_index
FROM race_context r
LEFT JOIN race_result_context rc ON rc.race_key = r.race_key
JOIN runner_pre p ON p.race_key = r.race_key
LEFT JOIN runner_result x ON x.race_key = p.race_key AND x.horse_no = p.horse_no
LEFT JOIN workout_main w ON w.race_key = p.race_key AND w.horse_no = p.horse_no
LEFT JOIN training_analysis t ON t.race_key = p.race_key AND t.horse_no = p.horse_no;
