PRAGMA foreign_keys=ON;

CREATE TABLE canonical_build (
  build_id INTEGER PRIMARY KEY,
  schema_version TEXT NOT NULL,
  parser_version TEXT NOT NULL,
  started_at TEXT NOT NULL,
  finished_at TEXT,
  status TEXT NOT NULL,
  years_json TEXT NOT NULL,
  source_manifest_json TEXT,
  integrity_check TEXT,
  message TEXT
);

CREATE TABLE source_archive (
  source_id INTEGER PRIMARY KEY,
  build_id INTEGER NOT NULL,
  source_kind TEXT NOT NULL,
  year INTEGER NOT NULL,
  archive_filename TEXT NOT NULL,
  archive_sha256 TEXT NOT NULL,
  archive_size_bytes INTEGER NOT NULL,
  member_count INTEGER NOT NULL,
  record_count INTEGER NOT NULL,
  imported_at TEXT NOT NULL,
  UNIQUE(build_id, source_kind, year),
  FOREIGN KEY(build_id) REFERENCES canonical_build(build_id)
);

CREATE TABLE bac_race (
  race_key_raw TEXT PRIMARY KEY,
  venue_code TEXT,
  year_yy TEXT,
  meeting_no_raw TEXT,
  day_raw TEXT,
  race_no INTEGER,
  date_raw TEXT,
  race_date TEXT,
  post_time_raw TEXT,
  post_time TEXT,
  distance_raw TEXT,
  distance_m INTEGER,
  surface_code TEXT,
  turn_code TEXT,
  layout_code TEXT,
  race_type_code TEXT,
  race_class_code TEXT,
  symbol_code TEXT,
  weight_rule_code TEXT,
  grade_code TEXT,
  race_name TEXT,
  meeting TEXT,
  field_size INTEGER,
  course_code TEXT,
  meeting_area_code TEXT,
  source_id INTEGER NOT NULL,
  source_member TEXT NOT NULL,
  record_hash TEXT NOT NULL,
  FOREIGN KEY(source_id) REFERENCES source_archive(source_id)
);

CREATE TABLE kyi_entry (
  race_key_raw TEXT NOT NULL,
  race_horse_key TEXT NOT NULL UNIQUE,
  horse_no INTEGER NOT NULL,
  blood_registration_no TEXT,
  horse_name TEXT,
  idm REAL,
  jockey_index REAL,
  info_index REAL,
  total_index REAL,
  running_style_code TEXT,
  distance_fit_code TEXT,
  improvement_code TEXT,
  rotation_interval INTEGER,
  base_win_odds REAL,
  base_win_rank INTEGER,
  base_place_odds REAL,
  base_place_rank INTEGER,
  training_index REAL,
  stable_index REAL,
  training_arrow_code TEXT,
  stable_evaluation_code TEXT,
  jockey_expected_top2_rate REAL,
  longshot_index REAL,
  hoof_code TEXT,
  heavy_track_fit_code TEXT,
  jrdb_class_code TEXT,
  blinker_code TEXT,
  jockey TEXT,
  carried_weight_tenths INTEGER,
  apprentice_code TEXT,
  trainer TEXT,
  trainer_base TEXT,
  frame_no INTEGER,
  condition_class_code TEXT,
  distance_fit2_code TEXT,
  body_weight_pre_kg INTEGER,
  body_weight_change_pre_kg INTEGER,
  cancel_flag TEXT,
  sex_code TEXT,
  mark_total TEXT,
  mark_idm TEXT,
  mark_info TEXT,
  mark_jockey TEXT,
  mark_stable TEXT,
  mark_training TEXT,
  mark_longshot TEXT,
  turf_fit_code TEXT,
  dirt_fit_code TEXT,
  jockey_code TEXT,
  trainer_code TEXT,
  pace_index_front REAL,
  pace_index_pace REAL,
  pace_index_late REAL,
  pace_index_position REAL,
  pace_rank_front INTEGER,
  pace_rank_pace INTEGER,
  pace_rank_late INTEGER,
  pace_rank_position INTEGER,
  forecast_pace_code TEXT,
  forecast_mid_min INTEGER,
  forecast_mid_max INTEGER,
  forecast_mid_code TEXT,
  forecast_last3f_min INTEGER,
  forecast_last3f_max INTEGER,
  forecast_last3f_code TEXT,
  forecast_finish_min INTEGER,
  forecast_finish_max INTEGER,
  forecast_finish_code TEXT,
  symbol_code TEXT,
  start_index REAL,
  late_break_rate REAL,
  stable_run_no INTEGER,
  stable_entry_date_raw TEXT,
  stable_entry_date TEXT,
  stable_days_before INTEGER,
  rest_reason_code TEXT,
  farm_name TEXT,
  farm_rank TEXT,
  farm_index_rank INTEGER,
  source_id INTEGER NOT NULL,
  source_member TEXT NOT NULL,
  record_hash TEXT NOT NULL,
  PRIMARY KEY(race_key_raw, horse_no),
  FOREIGN KEY(source_id) REFERENCES source_archive(source_id)
);

CREATE TABLE kyi_previous_link (
  race_key_raw TEXT NOT NULL,
  horse_no INTEGER NOT NULL,
  sequence INTEGER NOT NULL CHECK(sequence BETWEEN 1 AND 5),
  prev_result_key TEXT,
  prev_race_key_raw TEXT,
  PRIMARY KEY(race_key_raw, horse_no, sequence),
  FOREIGN KEY(race_key_raw, horse_no) REFERENCES kyi_entry(race_key_raw, horse_no)
);

CREATE TABLE kyi_trait (
  race_key_raw TEXT NOT NULL,
  horse_no INTEGER NOT NULL,
  sequence INTEGER NOT NULL CHECK(sequence BETWEEN 1 AND 6),
  trait_code TEXT,
  PRIMARY KEY(race_key_raw, horse_no, sequence),
  FOREIGN KEY(race_key_raw, horse_no) REFERENCES kyi_entry(race_key_raw, horse_no)
);

CREATE TABLE cha_workout (
  race_horse_key TEXT PRIMARY KEY,
  race_key_raw TEXT NOT NULL,
  horse_no INTEGER NOT NULL,
  weekday TEXT,
  workout_count INTEGER,
  date_raw TEXT,
  workout_date TEXT,
  course_code TEXT,
  strength_code TEXT,
  state_code TEXT,
  rider_type_code TEXT,
  furlongs INTEGER,
  clock_front_sec REAL,
  clock_middle_sec REAL,
  clock_last_sec REAL,
  clock_index_front INTEGER,
  clock_index_middle INTEGER,
  clock_index_last INTEGER,
  clock_index_total INTEGER,
  pair_result_code TEXT,
  pair_strength_code TEXT,
  pair_age INTEGER,
  pair_class_code TEXT,
  source_id INTEGER NOT NULL,
  source_member TEXT NOT NULL,
  record_hash TEXT NOT NULL,
  FOREIGN KEY(source_id) REFERENCES source_archive(source_id)
);

CREATE TABLE cyb_training (
  race_horse_key TEXT PRIMARY KEY,
  race_key_raw TEXT NOT NULL,
  horse_no INTEGER NOT NULL,
  training_type_code TEXT,
  training_course_type_code TEXT,
  course_count_slope INTEGER,
  course_count_wood INTEGER,
  course_count_dirt INTEGER,
  course_count_turf INTEGER,
  course_count_pool INTEGER,
  course_count_obstacle INTEGER,
  course_count_polytrack INTEGER,
  distance_pattern_code TEXT,
  focus_code TEXT,
  training_index INTEGER,
  condition_index INTEGER,
  volume_grade TEXT,
  condition_change_code TEXT,
  comment TEXT,
  comment_date_raw TEXT,
  comment_date TEXT,
  training_grade_code TEXT,
  one_week_ago_index INTEGER,
  one_week_ago_course TEXT,
  source_id INTEGER NOT NULL,
  source_member TEXT NOT NULL,
  record_hash TEXT NOT NULL,
  FOREIGN KEY(source_id) REFERENCES source_archive(source_id)
);

CREATE TABLE sed_result (
  result_key TEXT PRIMARY KEY,
  race_key_raw TEXT NOT NULL,
  horse_no INTEGER NOT NULL,
  blood_registration_no TEXT,
  date_raw TEXT,
  race_date TEXT,
  horse_name TEXT,
  race_name TEXT,
  distance_m INTEGER,
  surface_code TEXT,
  turn_code TEXT,
  layout_code TEXT,
  track_condition_code TEXT,
  race_type_code TEXT,
  race_class_code TEXT,
  race_symbol_code TEXT,
  weight_condition_code TEXT,
  grade_code TEXT,
  field_size INTEGER,
  finish INTEGER,
  abnormal_code TEXT,
  time_raw TEXT,
  carried_weight_tenths INTEGER,
  jockey TEXT,
  trainer TEXT,
  final_win_odds REAL,
  final_popularity_raw TEXT,
  final_popularity INTEGER,
  idm INTEGER,
  metric_raw_score INTEGER,
  metric_track_diff INTEGER,
  metric_pace_score INTEGER,
  metric_late_break_score INTEGER,
  metric_position_score INTEGER,
  metric_trouble_score INTEGER,
  metric_prev_trouble_score INTEGER,
  metric_mid_trouble_score INTEGER,
  metric_late_trouble_score INTEGER,
  metric_race_score INTEGER,
  metric_front_index REAL,
  metric_late_index REAL,
  metric_pace_index REAL,
  metric_race_pace_index REAL,
  course_lane_code TEXT,
  result_uptrend_code TEXT,
  result_class_code TEXT,
  mood_code TEXT,
  corner1 INTEGER,
  corner2 INTEGER,
  corner3 INTEGER,
  corner4 INTEGER,
  first_second_time_diff_sec REAL,
  first3f_sec REAL,
  last3f_sec REAL,
  first3f_leader_diff_sec REAL,
  last3f_leader_diff_sec REAL,
  race_pace_code TEXT,
  horse_pace_code TEXT,
  final_place_odds_lower REAL,
  jockey_code TEXT,
  trainer_code TEXT,
  body_weight_kg INTEGER,
  body_weight_change_kg INTEGER,
  weather_code TEXT,
  body_condition_code TEXT,
  course_code TEXT,
  race_running_style_code TEXT,
  win_payout INTEGER,
  place_payout INTEGER,
  fourth_corner_lane_code TEXT,
  start_time_raw TEXT,
  start_time TEXT,
  source_id INTEGER NOT NULL,
  source_member TEXT NOT NULL,
  record_hash TEXT NOT NULL,
  UNIQUE(race_key_raw, horse_no),
  FOREIGN KEY(source_id) REFERENCES source_archive(source_id)
);

CREATE TABLE skb_extension (
  result_key TEXT PRIMARY KEY,
  leg_overall_code TEXT,
  leg_left_front_code TEXT,
  leg_right_front_code TEXT,
  leg_left_hind_code TEXT,
  leg_right_hind_code TEXT,
  paddock_comment TEXT,
  leg_comment TEXT,
  equipment_comment TEXT,
  race_comment TEXT,
  source_id INTEGER NOT NULL,
  source_member TEXT NOT NULL,
  record_hash TEXT NOT NULL,
  FOREIGN KEY(source_id) REFERENCES source_archive(source_id)
);

CREATE TABLE skb_tokki (
  result_key TEXT NOT NULL,
  sequence INTEGER NOT NULL CHECK(sequence BETWEEN 1 AND 6),
  tokki_code TEXT,
  PRIMARY KEY(result_key, sequence),
  FOREIGN KEY(result_key) REFERENCES skb_extension(result_key)
);

CREATE TABLE skb_equipment (
  result_key TEXT NOT NULL,
  sequence INTEGER NOT NULL CHECK(sequence BETWEEN 1 AND 8),
  equipment_code TEXT,
  PRIMARY KEY(result_key, sequence),
  FOREIGN KEY(result_key) REFERENCES skb_extension(result_key)
);

CREATE TABLE ukc_profile (
  horse_id TEXT NOT NULL,
  horse_name TEXT,
  sex_code TEXT,
  coat_color_code TEXT,
  horse_symbol_code TEXT,
  sire_name TEXT,
  dam_name TEXT,
  broodmare_sire_name TEXT,
  birth_date_raw TEXT,
  birth_date TEXT,
  sire_birth_year INTEGER,
  dam_birth_year INTEGER,
  broodmare_sire_birth_year INTEGER,
  owner_name TEXT,
  owner_group_code TEXT,
  breeder_name TEXT,
  breeding_place TEXT,
  deregistered_flag TEXT,
  data_date_raw TEXT,
  data_date TEXT,
  sire_line_code TEXT,
  broodmare_sire_line_code TEXT,
  source_id INTEGER NOT NULL,
  source_member TEXT NOT NULL,
  record_hash TEXT NOT NULL,
  PRIMARY KEY(horse_id, source_member),
  FOREIGN KEY(source_id) REFERENCES source_archive(source_id)
);

CREATE INDEX ix_bac_race_date ON bac_race(race_date, race_key_raw);
CREATE INDEX ix_bac_venue_race ON bac_race(race_date, venue_code, race_no);
CREATE INDEX ix_kyi_horse ON kyi_entry(blood_registration_no, race_key_raw);
CREATE INDEX ix_kyi_jockey ON kyi_entry(jockey_code, race_key_raw);
CREATE INDEX ix_kyi_trainer ON kyi_entry(trainer_code, race_key_raw);
CREATE INDEX ix_kyi_prev_result ON kyi_previous_link(prev_result_key);
CREATE INDEX ix_kyi_prev_race ON kyi_previous_link(prev_race_key_raw);
CREATE INDEX ix_cha_race ON cha_workout(race_key_raw, horse_no);
CREATE INDEX ix_cyb_race ON cyb_training(race_key_raw, horse_no);
CREATE INDEX ix_sed_race ON sed_result(race_key_raw, horse_no);
CREATE INDEX ix_sed_horse_date ON sed_result(blood_registration_no, race_date DESC);
CREATE INDEX ix_sed_date ON sed_result(race_date, race_key_raw);
CREATE INDEX ix_ukc_horse_date ON ukc_profile(horse_id, data_date DESC);

CREATE VIEW v_pre_race_entry AS
SELECT
  b.race_date,
  b.venue_code,
  b.race_no,
  b.race_key_raw,
  b.post_time,
  b.distance_m,
  b.surface_code,
  b.turn_code,
  b.layout_code,
  b.race_type_code,
  b.race_class_code,
  b.symbol_code AS race_symbol_code,
  b.weight_rule_code,
  b.grade_code,
  b.race_name,
  b.field_size,
  k.horse_no,
  k.frame_no,
  k.blood_registration_no AS horse_id,
  k.horse_name,
  k.sex_code,
  k.jockey,
  k.jockey_code,
  k.trainer,
  k.trainer_code,
  k.idm AS pre_idm,
  k.training_index,
  k.stable_index,
  k.running_style_code,
  k.distance_fit_code,
  k.improvement_code,
  k.rotation_interval,
  c.workout_date,
  c.course_code AS workout_course_code,
  c.clock_index_total AS workout_index,
  y.training_type_code,
  y.training_course_type_code,
  y.condition_index
FROM bac_race b
JOIN kyi_entry k ON k.race_key_raw=b.race_key_raw
LEFT JOIN cha_workout c ON c.race_key_raw=k.race_key_raw AND c.horse_no=k.horse_no
LEFT JOIN cyb_training y ON y.race_key_raw=k.race_key_raw AND y.horse_no=k.horse_no;

CREATE VIEW v_result_full AS
SELECT
  s.*,
  e.leg_overall_code,
  e.leg_left_front_code,
  e.leg_right_front_code,
  e.leg_left_hind_code,
  e.leg_right_hind_code,
  e.paddock_comment,
  e.leg_comment,
  e.equipment_comment,
  e.race_comment
FROM sed_result s
LEFT JOIN skb_extension e ON e.result_key=s.result_key;
