-- JRDB Post-Race Review v0.1 logical schema.
--
-- This file freezes the persisted DuckDB/Parquet column contract. It is not
-- the Warehouse schema and must never be used to reinterpret fixed-width JRDB
-- bytes. Nullable derived fields remain NULL when evidence is unavailable.

CREATE TABLE fact_race_context (
    race_key VARCHAR NOT NULL,
    race_date DATE NOT NULL,
    venue_code VARCHAR,
    surface_code VARCHAR,
    distance_m INTEGER,
    field_size INTEGER,
    race_pace_code VARCHAR,
    race_pace_code_conflict BOOLEAN,
    winner_time_sec DOUBLE,
    first3f_reference_sec DOUBLE,
    first3f_candidate_count INTEGER,
    first3f_candidate_mad_sec DOUBLE,
    last3f_reference_sec DOUBLE,
    last3f_candidate_count INTEGER,
    last3f_candidate_mad_sec DOUBLE,
    pace_balance_sec DOUBLE,
    pace_balance_percentile DOUBLE,
    pace_shape VARCHAR,
    pace_sample_count INTEGER,
    pace_scope_level INTEGER,
    review_schema_version VARCHAR NOT NULL,
    review_logic_version VARCHAR NOT NULL
);

CREATE TABLE fact_race_review (
    race_key VARCHAR NOT NULL,
    race_date DATE NOT NULL,
    venue_code VARCHAR,
    surface_code VARCHAR,
    distance_m INTEGER,
    declared_class_group VARCHAR,
    winner_time_sec DOUBLE,
    historical_standard_time_sec DOUBLE,
    standard_sample_count INTEGER,
    standard_scope_level INTEGER,
    standard_confidence VARCHAR,
    standard_sample_start_date DATE,
    standard_sample_end_date DATE,
    day_adjustment_per_1000m_sec DOUBLE,
    day_adjustment_candidate_sec DOUBLE,
    day_track_adjustment_sec DOUBLE,
    day_adjustment_race_count INTEGER,
    minimum_day_adjustment_race_count INTEGER,
    day_adjustment_residual_mad_sec DOUBLE,
    day_adjustment_applied BOOLEAN,
    adjusted_standard_time_sec DOUBLE,
    time_delta_sec DOUBLE,
    time_delta_per_1000m DOUBLE,
    time_delta_basis VARCHAR,
    equivalent_class_group VARCHAR,
    class_equivalent_numeric DOUBLE,
    class_curve_monotonic BOOLEAN,
    pace_shape VARCHAR,
    baseline_version VARCHAR NOT NULL,
    review_schema_version VARCHAR NOT NULL,
    review_logic_version VARCHAR NOT NULL
);

CREATE TABLE fact_horse_performance (
    race_key VARCHAR NOT NULL,
    race_horse_key VARCHAR NOT NULL,
    horse_no INTEGER NOT NULL,
    race_date DATE NOT NULL,
    venue_code VARCHAR,
    surface_code VARCHAR,
    distance_m INTEGER,
    field_size INTEGER,
    declared_class_group VARCHAR,
    horse_id VARCHAR,
    horse_name VARCHAR,
    finish INTEGER,
    time_sec DOUBLE,
    winner_gap_sec DOUBLE,
    carried_weight_kg DOUBLE,
    frame_no INTEGER,
    declared_running_style_code VARCHAR,
    race_running_style_code VARCHAR,
    course_lane_code VARCHAR,
    course_lane_bucket VARCHAR,
    fourth_corner_lane_code VARCHAR,
    fourth_corner_lane_bucket VARCHAR,
    first3f_sec DOUBLE,
    last3f_sec DOUBLE,
    last3f_rank INTEGER,
    last3f_speed_percentile DOUBLE,
    first3f_leader_diff_sec DOUBLE,
    last3f_leader_diff_sec DOUBLE,
    closing_gain_sec DOUBLE,
    corner1_position INTEGER,
    corner2_position INTEGER,
    corner3_position INTEGER,
    corner4_position INTEGER,
    corner1_frontness DOUBLE,
    corner2_frontness DOUBLE,
    corner3_frontness DOUBLE,
    corner4_frontness DOUBLE,
    early_position_gain DOUBLE,
    middle_position_gain DOUBLE,
    late_position_gain DOUBLE,
    overall_position_gain DOUBLE,
    historical_standard_time_sec DOUBLE,
    adjusted_standard_time_sec DOUBLE,
    day_adjustment_candidate_sec DOUBLE,
    day_track_adjustment_sec DOUBLE,
    day_adjustment_applied BOOLEAN,
    horse_adjusted_delta_sec DOUBLE,
    horse_adjusted_delta_per_1000m DOUBLE,
    time_class_equivalent VARCHAR,
    time_class_equivalent_numeric DOUBLE,
    class_curve_monotonic BOOLEAN,
    pace_shape VARCHAR,
    start_delay_confidence VARCHAR,
    jrdb_track_diff DOUBLE,
    jrdb_pace_score DOUBLE,
    jrdb_late_break_score DOUBLE,
    jrdb_position_score DOUBLE,
    jrdb_trouble_score DOUBLE,
    jrdb_prev_trouble_score DOUBLE,
    jrdb_mid_trouble_score DOUBLE,
    jrdb_late_trouble_score DOUBLE,
    performance_label VARCHAR,
    reason_codes_json VARCHAR,
    baseline_version VARCHAR NOT NULL,
    review_schema_version VARCHAR NOT NULL,
    review_logic_version VARCHAR NOT NULL
);

CREATE TABLE fact_track_bias (
    race_date DATE NOT NULL,
    venue_code VARCHAR NOT NULL,
    surface_code VARCHAR NOT NULL,
    bias_dimension VARCHAR NOT NULL,
    bias_bucket VARCHAR NOT NULL,
    same_day_sample_count INTEGER,
    raw_time_performance_median DOUBLE,
    raw_time_performance_mean DOUBLE,
    raw_last3f_relative_median DOUBLE,
    raw_last3f_sample_count INTEGER,
    adjusted_performance_residual DOUBLE,
    adjusted_sample_count INTEGER,
    prior_sample_count INTEGER,
    raw_same_day_estimate DOUBLE,
    prior_estimate DOUBLE,
    prior_strength DOUBLE,
    shrunk_bias_score DOUBLE,
    bias_direction VARCHAR,
    confidence VARCHAR,
    baseline_version VARCHAR NOT NULL,
    review_schema_version VARCHAR NOT NULL,
    review_logic_version VARCHAR NOT NULL
);
